"""initial schema: extensions, enums, normalized store

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-26

Hand-written (NOT autogenerated). Alembic autogenerate does not reliably emit the
pgvector column type, the pgvector ANN index, or the Postgres enum types, so this
migration is authored by hand against the "Concrete schema" DDL in CLAUDE.md.

Order matters:
  1. extensions (vector for embeddings, pgcrypto for gen_random_uuid())
  2. enum types (created once, referenced by many tables)
  3. tables, parents before children (FK targets must exist first)
The pgvector HNSW index on voice_examples is deliberately deferred to Phase 6
(added "after the initial bulk load", per CLAUDE.md).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Enum value lists (must match app.models). Kept inline so the migration is a
# self-contained, replayable record of the schema at this point in time.
COMMENT_CATEGORY = (
    "spam",
    "simple_positive",
    "question",
    "brand_inquiry",
    "criticism",
    "sensitive",
    "other",
)
POLICY_ACTION = ("reply", "hide", "like", "ignore", "flag")
AUTONOMY_LEVEL = ("auto_send", "draft", "notify_only")
ACTION_STATUS = (
    "pending",
    "approved",
    "sent",
    "rejected",
    "auto_sent",
    "uncertain",
    "failed",
)
PLATFORM_KIND = ("youtube",)


# Enum type references for column definitions. create_type=False: the types are
# created explicitly below, so create_table must not try to CREATE TYPE again.
comment_category = postgresql.ENUM(
    *COMMENT_CATEGORY, name="comment_category", create_type=False
)
policy_action = postgresql.ENUM(*POLICY_ACTION, name="policy_action", create_type=False)
autonomy_level = postgresql.ENUM(
    *AUTONOMY_LEVEL, name="autonomy_level", create_type=False
)
action_status = postgresql.ENUM(*ACTION_STATUS, name="action_status", create_type=False)
platform_kind = postgresql.ENUM(*PLATFORM_KIND, name="platform_kind", create_type=False)


def _ts_columns() -> list[sa.Column]:
    """created_at / updated_at, timestamptz, defaulted in the DB."""
    return [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    ]


def _id_column() -> sa.Column:
    return sa.Column(
        "id",
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )


def upgrade() -> None:
    # 1. Extensions -------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # 2. Enum types -------------------------------------------------------------
    bind = op.get_bind()
    comment_category.create(bind, checkfirst=True)
    policy_action.create(bind, checkfirst=True)
    autonomy_level.create(bind, checkfirst=True)
    action_status.create(bind, checkfirst=True)
    platform_kind.create(bind, checkfirst=True)

    # 3. Tables (parents first) -------------------------------------------------
    op.create_table(
        "creators",
        _id_column(),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        *_ts_columns(),
        sa.UniqueConstraint("email", name="uq_creators_email"),
    )

    op.create_table(
        "platform_accounts",
        _id_column(),
        sa.Column(
            "creator_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("creators.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("platform", platform_kind, nullable=False),
        sa.Column("platform_account_id", sa.Text(), nullable=False),
        sa.Column("access_token_enc", sa.LargeBinary(), nullable=False),
        sa.Column("refresh_token_enc", sa.LargeBinary(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'connected'"), nullable=False
        ),
        *_ts_columns(),
        sa.UniqueConstraint(
            "platform", "platform_account_id", name="uq_platform_account_native"
        ),
    )
    op.create_index(
        "ix_platform_accounts_creator_id", "platform_accounts", ["creator_id"]
    )

    op.create_table(
        "llm_credentials",
        _id_column(),
        sa.Column(
            "creator_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("creators.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("api_key_enc", sa.LargeBinary(), nullable=False),
        sa.Column("key_hint", sa.Text(), nullable=False),
        *_ts_columns(),
    )
    op.create_index("ix_llm_credentials_creator_id", "llm_credentials", ["creator_id"])

    op.create_table(
        "posts",
        _id_column(),
        sa.Column(
            "platform_account_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("platform_accounts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("platform_post_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        *_ts_columns(),
        sa.UniqueConstraint(
            "platform_account_id", "platform_post_id", name="uq_post_native"
        ),
    )
    op.create_index("ix_posts_platform_account_id", "posts", ["platform_account_id"])

    op.create_table(
        "comments",
        _id_column(),
        sa.Column(
            "post_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("posts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("platform_comment_id", sa.Text(), nullable=False),
        sa.Column(
            "parent_comment_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("comments.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("author_name", sa.Text(), nullable=True),
        sa.Column("author_channel_id", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "is_reply", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "authored_by_creator",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category", comment_category, nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("classified_at", sa.DateTime(timezone=True), nullable=True),
        *_ts_columns(),
        sa.UniqueConstraint(
            "post_id", "platform_comment_id", name="uq_comment_native"
        ),
    )
    op.create_index("ix_comments_post_id", "comments", ["post_id"])

    op.create_table(
        "voice_examples",
        _id_column(),
        sa.Column(
            "platform_account_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("platform_accounts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("category", comment_category, nullable=False),
        sa.Column("parent_comment_text", sa.Text(), nullable=False),
        sa.Column("reply_text", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=True),
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
        *_ts_columns(),
        sa.UniqueConstraint(
            "platform_account_id",
            "category",
            "parent_comment_text",
            "reply_text",
            name="uq_voice_example_dedup",
        ),
    )
    op.create_index(
        "ix_voice_examples_platform_account_id",
        "voice_examples",
        ["platform_account_id"],
    )
    # NOTE: HNSW ANN index on `embedding` is added in Phase 6 after the initial
    # bulk load, per CLAUDE.md:
    #   CREATE INDEX ON voice_examples USING hnsw (embedding vector_cosine_ops);

    op.create_table(
        "category_policies",
        _id_column(),
        sa.Column(
            "creator_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("creators.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("platform", platform_kind, nullable=False),
        sa.Column("category", comment_category, nullable=False),
        sa.Column("action", policy_action, nullable=False),
        sa.Column("autonomy", autonomy_level, nullable=False),
        sa.Column("tone_constraint", sa.Text(), nullable=True),
        *_ts_columns(),
        sa.UniqueConstraint(
            "creator_id", "platform", "category", name="uq_policy_per_category"
        ),
    )
    op.create_index(
        "ix_category_policies_creator_id", "category_policies", ["creator_id"]
    )

    op.create_table(
        "actions",
        _id_column(),
        sa.Column(
            "comment_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("comments.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "creator_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("creators.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("category", comment_category, nullable=False),
        sa.Column("autonomy_decision", autonomy_level, nullable=False),
        sa.Column("draft_text", sa.Text(), nullable=True),
        sa.Column("final_text", sa.Text(), nullable=True),
        sa.Column(
            "status",
            action_status,
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("platform_reply_id", sa.Text(), nullable=True),
        sa.Column("approver", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        *_ts_columns(),
        # Idempotency backstop: one action per comment, ever.
        sa.UniqueConstraint("comment_id", name="uq_action_per_comment"),
    )
    op.create_index("ix_actions_creator_id", "actions", ["creator_id"])


def downgrade() -> None:
    # Drop children before parents; drop enum types last (nothing references them).
    op.drop_index("ix_actions_creator_id", table_name="actions")
    op.drop_table("actions")
    op.drop_index("ix_category_policies_creator_id", table_name="category_policies")
    op.drop_table("category_policies")
    op.drop_index(
        "ix_voice_examples_platform_account_id", table_name="voice_examples"
    )
    op.drop_table("voice_examples")
    op.drop_index("ix_comments_post_id", table_name="comments")
    op.drop_table("comments")
    op.drop_index("ix_posts_platform_account_id", table_name="posts")
    op.drop_table("posts")
    op.drop_index("ix_llm_credentials_creator_id", table_name="llm_credentials")
    op.drop_table("llm_credentials")
    op.drop_index(
        "ix_platform_accounts_creator_id", table_name="platform_accounts"
    )
    op.drop_table("platform_accounts")
    op.drop_table("creators")

    bind = op.get_bind()
    for enum_type in (
        action_status,
        autonomy_level,
        policy_action,
        platform_kind,
        comment_category,
    ):
        enum_type.drop(bind, checkfirst=True)

    op.execute("DROP EXTENSION IF EXISTS vector")
    # pgcrypto left in place — harmless, and other things may rely on it.
